# Generated by Django 3.0.8 on 2020-07-13 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_to_response', to='tweets.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweeted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweeted_by', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_response', to='tweets.Response')),
                ('tweet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_tweet', to='tweets.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='tweet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_to_tweet', to='tweets.Tweet'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_like', to='tweets.Response')),
                ('tweet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_like', to='tweets.Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
