# Generated by Django 3.0.8 on 2020-07-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='save',
        ),
    ]
