# Generated by Django 3.0.8 on 2020-07-27 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_tweet_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='save',
        ),
        migrations.AddField(
            model_name='tweet',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
