# Generated by Django 3.0.8 on 2020-08-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20200826_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_to', to='tweets.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
