export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_FAIL = 'REG_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const GET_USER = 'GET_USER'
export const LOADING = 'LOADING'
export const FOLLOWERS = 'FOLLOWERS'
export const FOLLOWING = 'FOLLOWING'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const UPDATE_USER = 'UPDATE_USER'

/*-----------------TWEETS-------------------*/

export const GET_TWEETS = 'GET_TWEETS'
export const GET_USER_TWEETS = 'GET_USER_TWEETS'
export const GET_USER_REPLIES = 'GET_USER_REPLIES'
export const GET_TWEET_DETAIL = 'GET_TWEET_DETAIL'
export const GET_LIKES = 'GET_LIKES'
export const GET_USER_LIKES = 'GET_USER_LIKES'
export const POST_TWEET = 'POST_TWEET'
export const DELETE_TWEET = 'DELETE_TWEET'
export const LIKE_TWEET = 'LIKE_TWEET'
export const LIKED_TWEETS = 'LIKED_TWEETS'
export const UNLIKE_TWEET = 'UNLIKE_TWEET'
export const GET_SAVED = 'GET_SAVED'
export const SAVE_TWEET = 'SAVE_TWEET'
export const REMOVE_SAVED_TWEET = 'REMOVE_SAVED_TWEET'
export const GET_REPLIES = 'GET_REPLIES'
export const POST_REPLY = 'POST_REPLY'
export const GET_RETWEETS = 'GET_RETWEETS'
export const RETWEET = 'RETWEET'
export const UNDO_RETWEET = 'UNDO_RETWEET'